-- create database EDA; 
USE EDA;
-- EXPLORATION OF THE DATABASE 
SELECT 
	TABLE_CATALOG,
	TABLE_SCHEMA,
	TABLE_NAME,
	TABLE_TYPE 
FROM INFORMATION_SCHEMA.TABLES; 
-- TO RETRIVE THE ALL THE COLUMNS IN THE DATASET 
SELECT 
	COLUMN_NAME,
	DATA_TYPE,
	IS_NULLABLE,
	CHARACTER_MAXIMUM_LENGTH 
FROM INFORMATION_SCHEMA.COLUMNS ; 